import Head from 'next/head'
import Image from 'next/image'
import Honeycomb from '../components/Honeycomb'
import Hexagon from '../components/Hexagon'
import styles from '../styles/Home.module.css'
import range from 'lodash/range'

const items = range(20)
const sideLength = 64
const hexClick = (item, index) => {
  console.log(`You clicked hex ${item}.`)
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <main className={styles.main}>
        <Honeycomb
          columns={5}
          size={sideLength}
          items={items}
          renderItem={(item, index) => (
            <Hexagon>
              <img
                onClick={() => hexClick(item, index)}
                src={`https://picsum.photos/${sideLength * 2}?random=${item}`}
                alt={`Random #${item}`}
              />
            </Hexagon>
          )}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  )
}
