import Head from 'next/head'
import Image from 'next/image'
import Honeycomb from '../components/Honeycomb'
import Hexagon from '../components/Hexagon'
import styles from '../styles/Home.module.css'
import range from 'lodash/range'
import Link from 'next/link'

const sideLength = 64
// TODO this data should be supplied to the API and rendered in the function
const NUM_COLUMNS = 5
const items = range(20).map(n => {
  const gCol = n % NUM_COLUMNS
  const gRow = Math.floor(n / NUM_COLUMNS)
  const q = gCol - (gRow + (gRow & 1)) / 2
  const r = gRow
  const s = -q - r
  return {
    index: n,
    column: gCol,
    row: gRow,
    q: q,
    r: r,
    s: s,
  }
})
const hexClick = (item, index) => {
  console.log(`coord: q${item.q}, r${item.r}, s${item.s}`)
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <Link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <main className={styles.main}>
        <Honeycomb
          columns={NUM_COLUMNS}
          size={sideLength}
          items={items}
          renderItem={(item, index) => (
            <Hexagon>
              <img
                onClick={() => hexClick(item, index)}
                src={`https://picsum.photos/${sideLength * 2}?random=${
                  item.index
                }`}
                alt={`Random #${item}`}
              />
            </Hexagon>
          )}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  )
}
